version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vitma_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vitma_network

volumes:
  pgdata:

networks:
  vitma_network:
    driver: bridge
