import * as Joi from 'joi';

export const validationSchema = Joi.object({
    NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
    BOT_TOKEN: Joi.string().required(),
    BOT_POLLING_ENABLED: Joi.boolean().default(true),
    PDF_DIR: Joi.string().default('storage/registrations'),
    CONSENT_DIR: Joi.string().default('storage/consents'),
    DB_HOST: Joi.string().trim().min(1).required(),
    DB_PORT: Joi.number().port().required(),
    DB_NAME: Joi.string().trim().min(1).required(),
    DB_USER: Joi.string().trim().min(1).required(),
    DB_PASS: Joi.string().trim().min(1).required(),
    TEST_DB_HOST: Joi.string().trim().min(1).optional(),
    TEST_DB_PORT: Joi.number().port().optional(),
    TEST_DB_NAME: Joi.when('NODE_ENV', {
        is: 'test',
        then: Joi.string().trim().min(1).required(),
        otherwise: Joi.string().trim().min(1).optional(),
    }),
    TEST_DB_USER: Joi.string().trim().min(1).optional(),
    TEST_DB_PASS: Joi.string().trim().min(1).optional(),
    MAX_BOT_TOKEN: Joi.string().optional(),
    ADMIN_SESSION_COOKIE_NAME: Joi.string().trim().min(1).default('vitma_admin_session'),
    ADMIN_SESSION_TTL_HOURS: Joi.number().integer().min(1).max(720).default(12),
    WEB_SESSION_COOKIE_NAME: Joi.string().trim().min(1).default('vitma_web_session'),
    WEB_SESSION_TTL_DAYS: Joi.number().integer().min(1).max(365).default(30),
    CORS_ORIGINS: Joi.string().allow('').optional(),
    TRUST_PROXY: Joi.string().allow('').optional(),
    SWAGGER_ENABLED: Joi.boolean().optional(),
    HTTP_JSON_LIMIT: Joi.string().pattern(/^\d+(kb|mb)$/i).default('256kb'),
    HTTP_URLENCODED_LIMIT: Joi.string().pattern(/^\d+(kb|mb)$/i).default('64kb'),
}).unknown(true);
